// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Storage } from '@capacitor/storage';
import type { Database } from './types';

const SUPABASE_URL = "https://ctwauyndeushfyxzzaxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0d2F1eW5kZXVzaGZ5eHp6YXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDE4MjYsImV4cCI6MjA3MTIxNzgyNn0.XuMG9PO8uQ7jdtHZLvGVeiidO8_816lNkStUGmGu7b8";

// Capacitor Storage adapter for Supabase auth persistence
const CapacitorStorage = {
  async getItem(key: string) {
    const { value } = await Storage.get({ key });
    return value;
  },
  async setItem(key: string, value: string) {
    await Storage.set({ key, value });
  },
  async removeItem(key: string) {
    await Storage.remove({ key });
  },
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: CapacitorStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
  }
);
